// Code generated by fabrik. DO NOT EDIT.

package main

import (
	"net/http"
	"os"

	"hello/web"
)

func run() error {
	// Providers
	webGreeter := web.NewGreeter()
	webHandlers := &web.Handlers{
		Greeter: webGreeter,
	}

	// Routes
	mux := http.NewServeMux()
	mux.HandleFunc("GET /", webHandlers.Index)

	addr := ":8080"
	if p := os.Getenv("PORT"); p != "" {
		addr = ":" + p
	}
	return http.ListenAndServe(addr, mux)
}
