package engine

import (
	"fmt"
	"sort"
	"strings"

	configdir "github.com/gofabrik/fabrik/config/directive"
	"github.com/gofabrik/fabrik/fabrik/internal/directives/core"
	"github.com/gofabrik/fabrik/gen"
	routerdir "github.com/gofabrik/fabrik/router/directive"
)

// New returns directive instances for one generation run.
func New() []gen.Directive {
	group := routerdir.NewGroup()
	routes := routerdir.NewRouteTable()
	// Configuration files are conventional: the base file plus a local
	// development overlay, both optional. Apps needing different sources
	// write a plain provider for their config struct instead.
	cfg := configdir.New("config.yaml", "config.local.yaml")
	provider := core.NewProvider(cfg)
	// Slice order is Finish order: directives whose Finish emits code
	// (http:server) come before validation-only finishers (config,
	// provider), which must observe everything materialized.
	return []gen.Directive{
		provider,
		core.NewSelect(provider, cfg),
		core.NewInit(cfg),
		routerdir.NewHTTP(group, routes),
		routerdir.NewHandle(group, routes),
		routerdir.NewStatic(routes),
		group,
		routerdir.NewMiddleware(),
		routerdir.NewNotFound(),
		routerdir.NewMethodNotAllowed(),
		routerdir.NewServe(),
		cfg,
	}
}

// DirectivesDoc renders the directive reference from registry metadata.
func DirectivesDoc() string {
	var b strings.Builder
	b.WriteString("# Directives\n")
	b.WriteString("\nGenerated by `fabrik directives`. Do not edit.\n")
	b.WriteString("\nEvery directive has the shape `//fabrik:NAME positional-args key=value-options`.\n")
	b.WriteString("Positional arguments come first, `key=value` options after; values may be\n")
	b.WriteString("double-quoted to contain spaces. Unknown option keys are errors, which is what\n")
	b.WriteString("makes new keys backwards-compatible additions.\n")

	directives := New()
	sort.Slice(directives, func(i, j int) bool { return directives[i].Name() < directives[j].Name() })
	for _, d := range directives {
		m := d.Meta()
		fmt.Fprintf(&b, "\n## fabrik:%s\n\n", d.Name())
		fmt.Fprintf(&b, "%s\n", m.Doc)
		if len(m.Pos) > 0 {
			b.WriteString("\nPositional arguments:\n\n")
			for _, p := range m.Pos {
				fmt.Fprintf(&b, "- `%s`%s\n", p.Name, valuesNote(p.Kind, p.Values))
			}
		}
		if len(m.Attrs) > 0 {
			b.WriteString("\nOptions:\n\n")
			for _, a := range m.Attrs {
				req := ""
				if a.Required {
					req = " (required)"
				}
				fmt.Fprintf(&b, "- `%s=`%s%s\n", a.Key, valuesNote(a.Kind, a.Values), req)
			}
		}
	}
	return b.String()
}

// valuesNote renders closed enum values or examples.
func valuesNote(kind gen.ValueKind, values []string) string {
	if len(values) == 0 {
		return ""
	}
	if kind == gen.KindEnum {
		return " - one of " + strings.Join(values, ", ")
	}
	return " - e.g. " + strings.Join(values, ", ")
}
