package engine

import (
	"fmt"
	"sort"
	"strings"

	assetsdir "github.com/gofabrik/fabrik/assetmapper/directive"
	clidir "github.com/gofabrik/fabrik/cli/directive"
	configdir "github.com/gofabrik/fabrik/config/directive"
	"github.com/gofabrik/fabrik/fabrik/internal/directives/core"
	"github.com/gofabrik/fabrik/gen"
	jobsdir "github.com/gofabrik/fabrik/jobs/directive"
	migdir "github.com/gofabrik/fabrik/migrations/directive"
	routerdir "github.com/gofabrik/fabrik/router/directive"
	tpldir "github.com/gofabrik/fabrik/templates/directive"
	webdir "github.com/gofabrik/fabrik/web/directive"
)

// New returns directive instances for one generation run.
func New() []gen.Directive {
	group := routerdir.NewGroup()
	routes := routerdir.NewRouteTable()
	mw := routerdir.NewMiddleware()
	host := routerdir.NewHost(group, routes, mw)
	tpl := tpldir.NewTemplates()
	// Conventional config layers are optional; custom sources belong in providers.
	cfg := configdir.New("config.yaml", "config.local.yaml")
	provider := core.NewProvider(cfg)
	jobsJob, jobsCron := jobsdir.New()
	// Registry order is presentation only; lifecycle order comes from Meta.Tier.
	return []gen.Directive{
		provider,
		core.NewSelect(provider, cfg),
		core.NewHook(cfg),
		routerdir.NewHTTP(host),
		routerdir.NewHandle(host),
		routerdir.NewStatic(host),
		group,
		mw,
		routerdir.NewNotFound(host),
		routerdir.NewMethodNotAllowed(host),
		webdir.NewWeb(host),
		tpl,
		tpldir.NewFuncs(tpl),
		assetsdir.NewAssets(host, tpl),
		migdir.NewMigrations(),
		jobsJob,
		jobsCron,
		clidir.New(),
		cfg,
	}
}

// DirectivesDoc renders the directive reference from registry metadata.
func DirectivesDoc() string {
	var b strings.Builder
	b.WriteString("# Directives\n")
	b.WriteString("\nGenerated by `fabrik directives`. Do not edit.\n")
	b.WriteString("\nEvery directive has the shape `//fabrik:NAME positional-args key=value-options`.\n")
	b.WriteString("Positional arguments come first, `key=value` options after; values may be\n")
	b.WriteString("double-quoted to contain spaces. Unknown option keys are errors, which is what\n")
	b.WriteString("makes new keys backwards-compatible additions.\n")

	directives := New()
	sort.Slice(directives, func(i, j int) bool { return directives[i].Name() < directives[j].Name() })
	for _, d := range directives {
		m := d.Meta()
		if m.Hidden {
			continue
		}
		fmt.Fprintf(&b, "\n## fabrik:%s\n\n", d.Name())
		fmt.Fprintf(&b, "%s\n", m.Doc)
		if len(m.Pos) > 0 {
			b.WriteString("\nPositional arguments:\n\n")
			for _, p := range m.Pos {
				fmt.Fprintf(&b, "- `%s`%s\n", p.Name, valuesNote(p.Kind, p.Values))
			}
		}
		if len(m.Attrs) > 0 {
			b.WriteString("\nOptions:\n\n")
			for _, a := range m.Attrs {
				req := ""
				if a.Required {
					req = " (required)"
				}
				fmt.Fprintf(&b, "- `%s=`%s%s\n", a.Key, valuesNote(a.Kind, a.Values), req)
			}
		}
	}
	return b.String()
}

func valuesNote(kind gen.ValueKind, values []string) string {
	if len(values) == 0 {
		return ""
	}
	if kind == gen.KindEnum {
		return " - one of " + strings.Join(values, ", ")
	}
	return " - e.g. " + strings.Join(values, ", ")
}
