// Code generated by fabrik. DO NOT EDIT.
// Regenerate with: fabrik wire

package main

import (
	"context"
	"fmt"

	"github.com/gofabrik/fabrik/assetmapper"
	"github.com/gofabrik/fabrik/config"
	"github.com/gofabrik/fabrik/migrations"
	"github.com/gofabrik/fabrik/router"
	"github.com/gofabrik/fabrik/templates"
	web2 "github.com/gofabrik/fabrik/web"

	"demo/auth"
	"demo/shared"
	"demo/web"
)

func run() error {
	ctx := context.Background()

	// Config
	sharedConfig, err := config.Load[shared.Config](
		config.FileOptional("config.yaml"),
		config.FileOptional("config.local.yaml"),
		config.KnownSections("database", "greeter", "http", "log"),
		config.Section("http"),
	)
	if err != nil {
		return err
	}

	sharedDatabase, err := config.Load[shared.Database](
		config.FileOptional("config.yaml"),
		config.FileOptional("config.local.yaml"),
		config.KnownSections("database", "greeter", "http", "log"),
		config.Section("database"),
	)
	if err != nil {
		return err
	}

	sharedLog, err := config.Load[shared.Log](
		config.FileOptional("config.yaml"),
		config.FileOptional("config.local.yaml"),
		config.KnownSections("database", "greeter", "http", "log"),
		config.Section("log"),
	)
	if err != nil {
		return err
	}

	webConfig, err := config.Load[web.Config](
		config.FileOptional("config.yaml"),
		config.FileOptional("config.local.yaml"),
		config.KnownSections("database", "greeter", "http", "log"),
		config.Section("greeter"),
	)
	if err != nil {
		return err
	}

	// Setup: after config, before providers
	if err := shared.InitLogger(sharedLog); err != nil {
		return err
	}

	// Providers
	sharedSqlDB, err := shared.NewDB(sharedDatabase)
	if err != nil {
		return err
	}
	authSqliteStore, err := auth.NewUsers(sharedSqlDB)
	if err != nil {
		return err
	}
	sharedQueryDialect := shared.NewQueryDialect()
	sharedSessionManager, err := shared.NewSession(sharedSqlDB)
	if err != nil {
		return err
	}
	authAuthsessionAuthenticator, err := auth.NewSessionAuth(sharedSessionManager)
	if err != nil {
		return err
	}
	authAuthAuthenticator := auth.NewAuthChain(authAuthsessionAuthenticator)
	authWebUI, err := auth.NewAuthUI(authSqliteStore, authAuthsessionAuthenticator, authAuthAuthenticator)
	if err != nil {
		return err
	}
	sharedFlash, err := shared.NewFlash(sharedSessionManager)
	if err != nil {
		return err
	}
	// web.Greeter, selected by greeter.kind
	var webGreeter web.Greeter
	switch webConfig.Kind {
	case "goodbye":
		webGreeter = web.NewGoodbyeGreeter()
	case "hello":
		webGreeter = web.NewHelloGreeter()
	default:
		return fmt.Errorf("no web.Greeter implementation for %q", webConfig.Kind)
	}
	authMount := &auth.Mount{
		UI: authWebUI,
	}
	webHandlers := &web.Handlers{
		Greeter: webGreeter,
		DB:      sharedSqlDB,
		Dialect: sharedQueryDialect,
		Session: sharedSessionManager,
		Flash:   sharedFlash,
	}
	webAPI := &web.API{
		Greeter: webGreeter,
	}

	assetCompiled, err := assetmapper.Build([]assetmapper.Root{
		{FS: shared.Assets, Dir: "assets"},
		{FS: web.Assets, Dir: "assets"},
	}, nil)
	if err != nil {
		return err
	}
	appTemplates, err := templates.LoadSources([]templates.Source{
		{FS: shared.Templates, Dir: "templates"},
		{FS: web.Templates, Dir: "templates"},
	}, assetCompiled.FuncMap(), templates.FuncMap{
		"humanizeAge": shared.HumanizeAge,
		"shout":       shared.Shout,
	})
	if err != nil {
		return err
	}
	sharedErrorPages := &shared.ErrorPages{
		Templates: appTemplates,
	}
	adapter := web2.NewAdapter(web2.WithRenderer(appTemplates))

	migrationSources := migrations.Sources{
		{Module: "shared", FS: shared.Migrations, Dir: "migrations"},
	}
	sharedMigrationsDialect := shared.NewDialect()

	r := router.New()
	webDocs := &web.Docs{
		Router: r,
	}

	sharedServer := &shared.Server{
		Config: sharedConfig,
	}

	// Start: after providers, before middleware and routes
	if err := shared.MigrateDB(ctx, sharedSqlDB, sharedMigrationsDialect, migrationSources); err != nil {
		return err
	}

	// Middleware
	optauthMW := auth.OptionalAuth(authAuthAuthenticator)
	r.Use(shared.Logged)
	r.Use(shared.Recovered)
	sessionMiddlewareMW := shared.SessionMiddleware(sharedSessionManager)
	r.Use(sessionMiddlewareMW)

	// Routes
	r.Handle("/auth/", authMount.Handler())
	r.Handle("/assets/", assetCompiled.Handler())
	r.NotFound(sharedErrorPages.NotFound)
	r.MethodNotAllowed(sharedErrorPages.MethodNotAllowed)
	r.Method("GET", "/{$}", adapter.Wrap(webHandlers.Index), shared.NoStore, optauthMW)
	r.Method("GET", "/api/greet/{name}", webAPI.Greet)
	r.Method("GET", "/routes", webDocs.List)

	// Serve
	return sharedServer.Serve(r)
}
