change_logs:
  default: CHANGELOG.md
default_change_logs:
  - default

components:
  - fabrik
  - assetmapper
  - cache
  - config
  - diag
  - flash
  - forms
  - gen
  - jobs
  - mail
  - migrations
  - query
  - ratelimit
  - router
  - session
  - storage
  - templates
  - validation
  - web
  - build
